export const styles = {
  container: {
    display: "flex",
    margin: "auto",
    color: "white",
    width: "100%",
    flexDirection: "column",
    padding: "0px 150px",
    fontSize: "15px",
  },
  customInput: {
    width: "100%",
    height: "50px",
    background: "rgba(210, 210, 210, 0.25)",
    border: "2px solid #d2d2d2",
    boxSizing: "border-box",
    borderRadius: "5px",
    padding: "10px 5px",
    color: "grey",
    fontSize: "15px",
  },
  textarea: {
    width: "100%",
    background: "rgba(210, 210, 210, 0.25)",
    border: "2px solid #d2d2d2",
    boxSizing: "border-box",
    borderRadius: "5px",
    padding: "1rem 5px",
    color: "white",
    fontSize: "15px",
    resize: "none"
  },
  customInputTitle: {
    width: "100%",
    height: "50px",
    background: "rgba(210, 210, 210, 0.25)",
    border: "2px solid #d2d2d2",
    boxSizing: "border-box",
    borderRadius: "5px",
    padding: "1rem 5px",
    color: "grey",
    fontSize: "15px",
  },
  customInputFile: {
    width: "100%",
    height: "50px",
    background: "rgba(210, 210, 210, 0.25)",
    border: "2px solid #d2d2d2",
    boxSizing: "border-box",
    borderRadius: "5px",
    padding: "1rem",
    color: "white",
    fontSize: "15px",
    width: "40%",
    justifySelf: "right",
    display: "none",
  },

  satuLine: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
  },
};
